from django.conf.urls import patterns, url
from stears import views

urlpatterns = patterns('',

                       # Basic URLs for main page and others:
                       url(r'^$', views.writers_home_test,
                           {'group': None}, name='home'),
                       url(r'^articles/$', views.writers_home_test,
                           {'group': None}, name='writers_home'),
                       url(r'^articlelist/(?P<group>[a-zA-Z0-9]+)/$',
                           views.writers_home_test, name='articles_group'),
                       url(r'^articles/allocate/$',
                           views.allocate_article, name='allocate'),
                       url(r'^articles/allocatereport/$',
                           views.allocate_report, name='allocate_report'),
                       url(r'^articles/allocator/$',
                           views.allocator, name='allocator'),
                       url(r'^articles/allocatedata/$',
                           views.economic_data, name='economic_data'),
                       url(r'^articles/relallocate/$',
                           views.reallocate_page, name='reallocate'),
                       url(r'^articles/reloadpage/$',
                           views.reload_page, name='reload'),
                       url(r'^articles/bin/$',
                           views.bin, name='bin'),
                       url(r'^articles/dctitle/$',
                           views.daily_column, name='daily_column'),
                       url(r'^articles/newquote/$',
                           views.new_quote, name='newquote'),
                       url(r'^articles/pipeline/$',
                           views.pipeline, name='pipeline'),
                       url(r'^articles/revive/$',
                           views.revive_article, name='revive'),
                       url(r'^articles/submissions/$',
                           views.submissions, name='submissions'),
                       url(r'^articles/write/$', views.writers_write,
                           name='writers_write'),

                       url(r'^article/addphoto/(?P<pk>[0-9]+)/$',
                           views.add_photo, name='addphoto'),
                       url(r'^article/addtag/(?P<pk>[0-9]+)/$',
                           views.add_tag, name='tag'),
                       url(r'^article/addwriter/$', views.add_writer_to_article,
                           name='add_writer'),
                       url(r'^article/approve/$',
                           views.approve_article, name='approve_article'),
                       url(r'^article/comment/(?P<pk>[0-9]+)/$',
                           views.comment, name='comment'),
                       url(r'^article/delete/$', views.delete_article,
                           name='delete_article'),
                       url(r'^article/detail/(?P<pk>[0-9]+)/$',
                           views.article_detail, name='article_detail'),
                       url(r'^article/preview/(?P<pk>[0-9]+)/$',
                           views.preview_article, name='preview'),
                       url(r'^article/prepreview/(?P<pk>[0-9]+)/$',
                           views.preview_prearticle, name='prepreview'),
                       url(r'^article/retract/$',
                           views.retract_article, name='retract'),
                       url(r'^article/removetag/(?P<pk>[0-9]+)$',
                           views.remove_tag, name='remove_tag'),
                       url(r'^article/removewriter/$', views.remove_writer_from_article,
                           name='remove_writer'),
                       url(r'^article/review/(?P<pk>[0-9]+)/$', views.review_article,
                           name='review'),
                       url(r'^article/submit/$', views.submit_article,
                           name='submit'),
                       url(r'^article/suggest/$', views.suggest,
                           name='suggest_nse_article'),
                       url(r'^article/summary/$', views.article_summary,
                           name='summary'),
                       url(r'^column/select/$', views.select_column,
                           name='select_column'),
                       url(r'^columns/$', views.column_master,
                           name='columns'),
                       url(r'^columns/launch/(?P<column_id>[0-9]+)$', views.launch_column,
                           name='launch_column'),
                        url(r'^columns/retract/(?P<column_id>[0-9]+)$', views.retract_column,
                           name='retract_column'),
                       url(r'^columns/new/$', views.add_column,
                           name='add_column'),
                       url(r'^columns/preview/(?P<column_id>[0-9]+)/$', views.preview_column,
                           name='preview_column'),
                       url(r'^columns/preview/(?P<column_id>[0-9]+)/article/(?P<pk>[0-9]+)$', views.preview_column,
                           name='preview_column'),

                       url(r'^changepassword/$', views.change_password,
                           name='change_password'),
                       url(r'^forgotpassword/$', views.forgot_password,
                           name='forgot_password'),
                       url(r'^login/$', views.login_view, name='login'),
                       url(r'^logout/$', views.logout_view, name='logout'),
                       url(r'^noaccess/$', views.noaccess, name='noaccess'),
                       url(r'^register/$', views.register, name='register'),


                       url(r'^gts/$', views.gts, name='gts'),
                       url(r'^photos/$', views.upload_photo,
                           name='photos'),
                       url(r'^photo/delete/$', views.delete_photo,
                           name='delete_photo'),
                       url(r'^photo/edit/$', views.edit_photo,
                           name='edit_photo'),
                       url(r'^reports/delete/$', views.delete_report,
                           name='del_report'),
                       url(r'^research/$', views.research, name='research'),

                       url(r'^writers/$', views.writers_list,
                           name='writers_list'),

                       url(r'^writer/accept/$',
                           views.accept_article_category, name='accept_article'),
                       url(r'^writer/approve/$', views.approve_writer,
                           name='approve_writer'),
                       url(r'^writer/details/(?P<name>[a-zA-Z0-9_]+)/$',
                           views.writer_detail, name='writer_detail'),
                       url(r'^writer/detail/edit/$',
                           views.edit_writer_detail, name='edit_writer_detail'),


                       # url(r'^writers/rich_text/$', views.edit_rich_text,
                       #     name='rich_text'),


                       # url(r'^articles/(?P<year>[0-9]{4})/$', views.year_archive),
                       # url(r'^articles/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.month_archive),
                       # url(r'^articles/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/$', views.day_archive),
                       # url(r'^articles/article/?P<pk>\d+/$',views.article_detail),

                       # url(r'^details/$', views.details, name='details'),
                       )
